"""initial schema

Revision ID: 26d8aab782aa
Revises: 
Create Date: 2026-05-21 16:09:46.342646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d8aab782aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('trademark_name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_trademark_name'), 'customers', ['trademark_name'], unique=True)
    op.create_table('products',
    sa.Column('rp_code', sa.String(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_rp_code'), 'products', ['rp_code'], unique=True)
    op.create_table('product_variants',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('packaging_type', sa.String(), nullable=True),
    sa.Column('packaging_volume_ml', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_customer_id'), 'product_variants', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('specifications',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'NEEDS_VERIFICATION', name='specificationstatusenum'), nullable=False),
    sa.Column('appearance', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('smell', sa.String(), nullable=True),
    sa.Column('ph_min', sa.Float(), nullable=True),
    sa.Column('ph_max', sa.Float(), nullable=True),
    sa.Column('viscosity_norm', sa.String(), nullable=True),
    sa.Column('density_norm', sa.String(), nullable=True),
    sa.Column('colloid_norm', sa.String(), nullable=True),
    sa.Column('thermo_norm', sa.String(), nullable=True),
    sa.Column('micro_total_norm', sa.String(), nullable=True),
    sa.Column('micro_yeast_norm', sa.String(), nullable=True),
    sa.Column('storage_conditions', sa.String(), nullable=True),
    sa.Column('shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('pao_months', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specifications_product_id'), 'specifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_specifications_spec_id'), 'specifications', ['spec_id'], unique=True)
    op.create_table('bulk_batches',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('date_mfg', sa.Date(), nullable=False),
    sa.Column('volume_kg', sa.Float(), nullable=True),
    sa.Column('appearance_fact', sa.String(), nullable=True),
    sa.Column('color_fact', sa.String(), nullable=True),
    sa.Column('smell_fact', sa.String(), nullable=True),
    sa.Column('ph_fact', sa.Float(), nullable=True),
    sa.Column('density_fact', sa.Float(), nullable=True),
    sa.Column('viscosity_fact', sa.String(), nullable=True),
    sa.Column('viscosity_unit', sa.String(), nullable=True),
    sa.Column('colloid_fact', sa.String(), nullable=True),
    sa.Column('thermo_fact', sa.String(), nullable=True),
    sa.Column('micro_total_fact', sa.String(), nullable=True),
    sa.Column('micro_yeast_fact', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('arbitrary_samples_taken', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.Enum('OK', 'OUT', name='verdictenum'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_batches_batch_number'), 'bulk_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_bulk_batches_product_id'), 'bulk_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_bulk_batches_specification_id'), 'bulk_batches', ['specification_id'], unique=False)
    op.create_table('finished_batches',
    sa.Column('bulk_batch_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('batch_number_gp', sa.String(), nullable=False),
    sa.Column('date_filling', sa.Date(), nullable=False),
    sa.Column('date_aroma_added', sa.Date(), nullable=True),
    sa.Column('quantity_units', sa.Integer(), nullable=True),
    sa.Column('allowed_for_shipment', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bulk_batch_id'], ['bulk_batches.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finished_batches_batch_number_gp'), 'finished_batches', ['batch_number_gp'], unique=False)
    op.create_index(op.f('ix_finished_batches_bulk_batch_id'), 'finished_batches', ['bulk_batch_id'], unique=False)
    op.create_index(op.f('ix_finished_batches_product_variant_id'), 'finished_batches', ['product_variant_id'], unique=False)
    op.create_table('quality_certificates',
    sa.Column('finished_batch_id', sa.Integer(), nullable=False),
    sa.Column('passport_no', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'REVOKED', name='certificatestatusenum'), nullable=False),
    sa.Column('verdict_text', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['finished_batch_id'], ['finished_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_certificates_finished_batch_id'), 'quality_certificates', ['finished_batch_id'], unique=False)
    op.create_index(op.f('ix_quality_certificates_passport_no'), 'quality_certificates', ['passport_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_certificates_passport_no'), table_name='quality_certificates')
    op.drop_index(op.f('ix_quality_certificates_finished_batch_id'), table_name='quality_certificates')
    op.drop_table('quality_certificates')
    op.drop_index(op.f('ix_finished_batches_product_variant_id'), table_name='finished_batches')
    op.drop_index(op.f('ix_finished_batches_bulk_batch_id'), table_name='finished_batches')
    op.drop_index(op.f('ix_finished_batches_batch_number_gp'), table_name='finished_batches')
    op.drop_table('finished_batches')
    op.drop_index(op.f('ix_bulk_batches_specification_id'), table_name='bulk_batches')
    op.drop_index(op.f('ix_bulk_batches_product_id'), table_name='bulk_batches')
    op.drop_index(op.f('ix_bulk_batches_batch_number'), table_name='bulk_batches')
    op.drop_table('bulk_batches')
    op.drop_index(op.f('ix_specifications_spec_id'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_product_id'), table_name='specifications')
    op.drop_table('specifications')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_customer_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_products_rp_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_trademark_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
